# Source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # Test golangci-lint for go-version define in go.mod
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 #v6.2.0
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 #v9.2.0
        with:
          version: latest
          only-new-issues: true

  # Test with EPUBCheck and send test coverage
  test-epubcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

    # This needs to come after the checkout, which wipes the working directory
    - name: Download EPUBCheck
      run: |
        # Download the latest version of EPUBCheck
        wget $(curl -Ls -H "Accept: application/vnd.github.v3+json" 'https://api.github.com/repos/IDPF/epubcheck/releases?per_page=1' | jq '.[0].assets[0].browser_download_url' -r)
        unzip epubcheck-*.zip

    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 #v6.2.0
      with:
        go-version-file: ./go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # 5.5.2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Test Mac and Windows with the latest version of Go
  test-mac-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 #v6.2.0
      with:
        go-version-file: ./go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
