name : "golangci-lint"

on:
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: golangci/golangci-lint-action@v3.7.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          go-version: '1.20'
